FirstName = input("Enter First Name: ")
MiddleName = input("Enter Middle Name: ")
LastName = input("Enter Last Name: ")
BirthDay = input("Enter Birthday: ")
Gender = input("Enter Gender: ")
Address = input("Enter Address: ")
Course = input("Enter Course: ")
YearLevel = input("Enter Year Level: ")

print("First Name:  ", FirstName)
print("Middle Name: ", MiddleName)
print("Last Name:   ", LastName)
print("Birthday:    ", BirthDay)
print("Gender:      ", Gender)
print("Address:     ", Address)
print("Course:      ", Course)
print("Year Level:  ", YearLevel)